const listOfHousings = [
    "--Undecided/Flexible--",
    "Dykstra",
    "Hedrick",
    "Rieber",
    "Sproul",
    "Hedrick Summit",
    "Rieber Terrace",
    "Rieber Vista",
    "Sunset Village",
    "De Neve Plaza",
    "Hitch",
    "Saxon",
    "Holly",
    "Gardenia",
    "Sproul Cove",
    "Sproul Landing",
    "Olympic",
    "Centennial",
    "Gayley Court",
    "Gayley Heights",
    "Gayley Towers",
    "Glenrock",
    "Glenrock West",
    "Landfair",
    "Landfair Vista",
    "Laurel",
    "Levering Terrace",
    "Palo Verde",
    "Tipuana",
    "Westwood Chateau",
    "Westwood Palms",
    "Weyburn Terrace",
    "Hilgard Houses",
    "University Village",
    "Rose Avenue Apartments",
    "Keystone/Mentone",
    "Venice/Barry",
    "The Boulevard",
    "UCHA",
    "Off-Campus"
];

export default listOfHousings;