const listOfDepartments = [
    "International and Area Studies",
    "American Indian Studies",
    "English",
    "Near Eastern Languages and Cultures",
    "Anthropology",
    "Art History",
    "Asian American Studies",
    "Asian Languages and Cultures",
    "Physics and Astronomy",
    "Atmospheric and Oceanic Sciences",
    "Physical Sciences",
    "Chemistry and Biochemistry",
    "Ecology and Evolutionary Biology",
    "Economics",
    "Slavic, East European, and Eurasian Languages and Cultures",
    "Chicana/o and Central American Studies",
    "Classics",
    "Psychology",
    "Communication",
    "Comparative Literature",
    "Computational and Systems Biology",
    "Earth, Planetary, and Space Sciences",
    "Ecology and Evolutionary Biology",
    "Environment and Sustainability",
    "European Languages and Transcultural Studies",
    "Gender Studies",
    "Geography",
    "History",
    "Labor Studies",
    "Linguistics",
    "Physical Science",
    "Microbiology, Immunology, and Molecular Genetics",
    "Molecular, Cell, and Developmental Biology",
    "Neuroscience",
    "Philosophy",
    "Physics and Astronomy",
    "Integrative Biology and Physiology",
    "Political Science",
    "Spanish and Portugues",
    "Humanities",
    "Sociology",
    "Statistics",
    "Interdisciplinary Studies",
    "Undeclared",
    "School of the Arts and Architecture",
    "Samueli School of Engineering",
    "Herb Alpert School of Music",
    "School of Nursing",
    "Luskin School of Pubic Affairs",
    "TFT",
    "Other"
];

export default listOfDepartments;